INSERT INTO Classes VALUES (1, 1)
INSERT INTO Classes VALUES (2, 1)
INSERT INTO Classes VALUES (3, 1)
INSERT INTO Classes VALUES (4, 1)
INSERT INTO Classes VALUES (5, 1)
GO

INSERT INTO Classes VALUES (6, 2)
INSERT INTO Classes VALUES (7, 2)
INSERT INTO Classes VALUES (8, 2)
INSERT INTO Classes VALUES (9, 2)
INSERT INTO Classes VALUES (10, 2)
GO

INSERT INTO Classes VALUES (1, 3)
INSERT INTO Classes VALUES (3, 3)
INSERT INTO Classes VALUES (7, 3)
GO

INSERT INTO Classes VALUES (11, 4)
INSERT INTO Classes VALUES (13, 4)
INSERT INTO Classes VALUES (15, 4)
GO

INSERT INTO Classes VALUES (12, 5)
INSERT INTO Classes VALUES (14, 5)
GO

INSERT INTO Classes VALUES (16, 6)
INSERT INTO Classes VALUES (18, 6)
INSERT INTO Classes VALUES (19, 6)
INSERT INTO Classes VALUES (20, 6)
GO

INSERT INTO Classes VALUES (17, 7)
GO

INSERT INTO Classes VALUES (21, 8)
INSERT INTO Classes VALUES (22, 8)
INSERT INTO Classes VALUES (23, 8)
INSERT INTO Classes VALUES (24, 8)
INSERT INTO Classes VALUES (25, 8)
GO

INSERT INTO Classes VALUES (26, 9)
INSERT INTO Classes VALUES (27, 9)
INSERT INTO Classes VALUES (28, 9)
INSERT INTO Classes VALUES (29, 9)
INSERT INTO Classes VALUES (30, 9)
GO

INSERT INTO Classes VALUES (31, 10)
INSERT INTO Classes VALUES (32, 10)
INSERT INTO Classes VALUES (33, 10)
GO

INSERT INTO Classes VALUES (31, 11)
INSERT INTO Classes VALUES (32, 11)
GO

INSERT INTO Classes VALUES (34, 12)
INSERT INTO Classes VALUES (35, 12)
GO