-- Data in this file is generated by computer programs for testing purposes. --

INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Mr', 'John', 'Smith', 'DPhil Mathematics')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Dr', 'Emily', 'Johnson', 'PhD Applied Mathematics')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Prof', 'David', 'Brown', 'MSc Mathematical Physics')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Ms', 'Sophia', 'Clark', 'MSc Mathematics and Statistics')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Mr', 'Daniel', 'Anderson', 'MPhil Mathematical Modeling')
GO

INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Dr', 'Sophia', 'Chang', 'PhD Neuroscience')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Ms', 'Elena', 'Garcia', 'MSc Biochemistry')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Mr', 'Jonathan', 'Nguyen', 'BSc Computer Science')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Mr', 'David', 'Lopez', 'MSc Mathematics')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Ms', 'Sarah', 'Jackson', 'BSc Physics')
GO

INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Mr', 'Christopher', 'Davis', 'MA Fine Arts')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Ms', 'Emma', 'Robinson', 'MFA Creative Writing')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Mr', 'Alexander', 'Lee', 'BA Music Composition')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Ms', 'Olivia', 'Gordon', 'BFA Acting')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Mrs', 'Isabella', 'Martinez', 'MA Graphic Design')
GO

INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Dr', 'Andrew', 'Wang', 'PhD Economics')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Ms', 'Sophie', 'Li', 'MSc Finance')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Mr', 'Benjamin', 'Gomez', 'BSc Accounting')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Dr', 'Rachel', 'Chen', 'PhD Business Administration')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Ms', 'Victoria', 'Nguyen', 'MSc Econometrics')
GO

INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Dr', 'William', 'Jones', 'PhD History')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Ms', 'Elizabeth', 'Brown', 'MA European History')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Mr', 'Daniel', 'Smith', 'BA Ancient History')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Dr', 'Emmy', 'Johnson', 'PhD American History')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Ms', 'Sophia', 'Davis', 'MA World History')
GO

INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Dr', 'David', 'Roberts', 'PhD Physical Geography')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Ms', 'Emma', 'Wilson', 'MSc Human Geography')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Mr', 'Daniel', 'Harris', 'BSc Geographical Information Systems')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Dr', 'Rachel', 'Jackson', 'PhD Environmental Geography')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Ms', 'Sophia', 'Thompson', 'MSc Urban Geography')
GO

INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Dr', 'Isabella', 'Lopez', 'PhD Linguistics')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Ms', 'Sophie', 'Garcia', 'MA English Literature')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Mr', 'Daniel', 'Chen', 'BA French Studies')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Dr', 'Emily', 'Nguyen', 'PhD Spanish Language')
INSERT INTO Teachers (Title, FirstName, LastName, Qualification) VALUES ('Ms', 'Olivia', 'Wang', 'MSc Translation Studies')
GO

INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Emma', 'Johnson', '2006-03-21')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Noah', 'Martinez', '2005-08-15')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Olivia', 'Garcia', '2007-05-09')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Liam', 'Brown', '2006-11-28')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Sophia', 'Nguyen', '2005-09-04')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('William', 'Rodriguez', '2007-02-17')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Isabella', 'Lopez', '2006-06-30')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('James', 'Hernandez', '2005-12-23')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Sophia', 'Martinez', '2007-10-10')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Benjamin', 'Wang', '2006-04-05')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Charlotte', 'Chen', '2005-07-12')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Mason', 'Tran', '2007-01-03')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Amelia', 'Nguyen', '2006-09-19')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Elijah', 'Gonzalez', '2005-02-14')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Ava', 'Harris', '2007-08-08')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Oliver', 'Davis', '2006-12-31')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Harper', 'Jackson', '2005-10-26')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Ethan', 'Thompson', '2007-06-15')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Evelyn', 'White', '2006-11-09')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Michael', 'Lee', '2005-04-24')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Avery', 'Wong', '2007-03-19')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Elena', 'Taylor', '2006-07-04')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Alexander', 'Martinez', '2005-09-27')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Scarlett', 'Kim', '2007-01-12')
INSERT INTO Students (FirstName, LastName, DateOfBirth) VALUES ('Lucas', 'Wilson', '2006-05-07')
GO

-- Data in this file is generated by computer programs for testing purposes. --