INSERT INTO ClassSets VALUES (1, 1)
INSERT INTO ClassSets VALUES (2, 1)
INSERT INTO ClassSets VALUES (3, 1)
INSERT INTO ClassSets VALUES (4, 1)
INSERT INTO ClassSets VALUES (5, 1)
GO

INSERT INTO ClassSets VALUES (6, 2)
INSERT INTO ClassSets VALUES (7, 2)
INSERT INTO ClassSets VALUES (8, 2)
INSERT INTO ClassSets VALUES (9, 2)
INSERT INTO ClassSets VALUES (10, 2)
GO

INSERT INTO ClassSets VALUES (1, 3)
INSERT INTO ClassSets VALUES (3, 3)
INSERT INTO ClassSets VALUES (7, 3)
GO

INSERT INTO ClassSets VALUES (11, 4)
INSERT INTO ClassSets VALUES (13, 4)
INSERT INTO ClassSets VALUES (15, 4)
GO

INSERT INTO ClassSets VALUES (12, 5)
INSERT INTO ClassSets VALUES (14, 5)
GO

INSERT INTO ClassSets VALUES (16, 6)
INSERT INTO ClassSets VALUES (18, 6)
INSERT INTO ClassSets VALUES (19, 6)
INSERT INTO ClassSets VALUES (20, 6)
GO

INSERT INTO ClassSets VALUES (17, 7)
GO

INSERT INTO ClassSets VALUES (21, 8)
INSERT INTO ClassSets VALUES (22, 8)
INSERT INTO ClassSets VALUES (23, 8)
INSERT INTO ClassSets VALUES (24, 8)
INSERT INTO ClassSets VALUES (25, 8)
GO

INSERT INTO ClassSets VALUES (26, 9)
INSERT INTO ClassSets VALUES (27, 9)
INSERT INTO ClassSets VALUES (28, 9)
INSERT INTO ClassSets VALUES (29, 9)
INSERT INTO ClassSets VALUES (30, 9)
GO

INSERT INTO ClassSets VALUES (31, 10)
INSERT INTO ClassSets VALUES (32, 10)
INSERT INTO ClassSets VALUES (33, 10)
GO

INSERT INTO ClassSets VALUES (31, 11)
INSERT INTO ClassSets VALUES (32, 11)
GO

INSERT INTO ClassSets VALUES (34, 12)
INSERT INTO ClassSets VALUES (35, 12)
GO