INSERT INTO ClassEnrollments VALUES (1, 1)
INSERT INTO ClassEnrollments VALUES (2, 1)
INSERT INTO ClassEnrollments VALUES (3, 1)
INSERT INTO ClassEnrollments VALUES (4, 1)
INSERT INTO ClassEnrollments VALUES (5, 1)
INSERT INTO ClassEnrollments VALUES (6, 2)
INSERT INTO ClassEnrollments VALUES (7, 2)
INSERT INTO ClassEnrollments VALUES (8, 2)
INSERT INTO ClassEnrollments VALUES (9, 2)
INSERT INTO ClassEnrollments VALUES (10, 2)
INSERT INTO ClassEnrollments VALUES (11, 3)
INSERT INTO ClassEnrollments VALUES (12, 3)
INSERT INTO ClassEnrollments VALUES (13, 3)
INSERT INTO ClassEnrollments VALUES (14, 3)
INSERT INTO ClassEnrollments VALUES (15, 3)
INSERT INTO ClassEnrollments VALUES (16, 4)
INSERT INTO ClassEnrollments VALUES (17, 4)
INSERT INTO ClassEnrollments VALUES (18, 4)
INSERT INTO ClassEnrollments VALUES (19, 4)
INSERT INTO ClassEnrollments VALUES (20, 4)
INSERT INTO ClassEnrollments VALUES (21, 5)
INSERT INTO ClassEnrollments VALUES (22, 5)
INSERT INTO ClassEnrollments VALUES (23, 5)
INSERT INTO ClassEnrollments VALUES (24, 5)
INSERT INTO ClassEnrollments VALUES (25, 5)
GO

INSERT INTO ClassEnrollments VALUES (1, 6)
INSERT INTO ClassEnrollments VALUES (2, 6)
INSERT INTO ClassEnrollments VALUES (3, 6)
INSERT INTO ClassEnrollments VALUES (4, 6)
INSERT INTO ClassEnrollments VALUES (5, 6)
INSERT INTO ClassEnrollments VALUES (6, 7)
INSERT INTO ClassEnrollments VALUES (7, 7)
INSERT INTO ClassEnrollments VALUES (8, 7)
INSERT INTO ClassEnrollments VALUES (9, 7)
INSERT INTO ClassEnrollments VALUES (10, 7)
INSERT INTO ClassEnrollments VALUES (11, 8)
INSERT INTO ClassEnrollments VALUES (12, 8)
INSERT INTO ClassEnrollments VALUES (13, 8)
INSERT INTO ClassEnrollments VALUES (14, 8)
INSERT INTO ClassEnrollments VALUES (15, 8)
INSERT INTO ClassEnrollments VALUES (16, 9)
INSERT INTO ClassEnrollments VALUES (17, 9)
INSERT INTO ClassEnrollments VALUES (18, 9)
INSERT INTO ClassEnrollments VALUES (19, 9)
INSERT INTO ClassEnrollments VALUES (20, 9)
INSERT INTO ClassEnrollments VALUES (21, 10)
INSERT INTO ClassEnrollments VALUES (22, 10)
INSERT INTO ClassEnrollments VALUES (23, 10)
INSERT INTO ClassEnrollments VALUES (24, 10)
INSERT INTO ClassEnrollments VALUES (25, 10)
GO

INSERT INTO ClassEnrollments VALUES (2, 11)
INSERT INTO ClassEnrollments VALUES (3, 11)
INSERT INTO ClassEnrollments VALUES (5, 11)
INSERT INTO ClassEnrollments VALUES (7, 11)
INSERT INTO ClassEnrollments VALUES (11, 11)
INSERT INTO ClassEnrollments VALUES (13, 12)
INSERT INTO ClassEnrollments VALUES (17, 12)
INSERT INTO ClassEnrollments VALUES (19, 12)
INSERT INTO ClassEnrollments VALUES (21, 12)
INSERT INTO ClassEnrollments VALUES (23, 12)
INSERT INTO ClassEnrollments VALUES (12, 13)
INSERT INTO ClassEnrollments VALUES (14, 13)
INSERT INTO ClassEnrollments VALUES (16, 13)
INSERT INTO ClassEnrollments VALUES (18, 13)
INSERT INTO ClassEnrollments VALUES (20, 13)
GO

INSERT INTO ClassEnrollments VALUES (3, 14)
INSERT INTO ClassEnrollments VALUES (4, 14)
INSERT INTO ClassEnrollments VALUES (6, 14)
INSERT INTO ClassEnrollments VALUES (8, 14)
INSERT INTO ClassEnrollments VALUES (12, 14)
INSERT INTO ClassEnrollments VALUES (14, 15)
INSERT INTO ClassEnrollments VALUES (18, 15)
INSERT INTO ClassEnrollments VALUES (20, 15)
INSERT INTO ClassEnrollments VALUES (22, 15)
INSERT INTO ClassEnrollments VALUES (24, 15)
INSERT INTO ClassEnrollments VALUES (13, 16)
INSERT INTO ClassEnrollments VALUES (16, 16)
INSERT INTO ClassEnrollments VALUES (17, 16)
INSERT INTO ClassEnrollments VALUES (19, 16)
INSERT INTO ClassEnrollments VALUES (21, 16)
GO

INSERT INTO ClassEnrollments VALUES (2, 17)
INSERT INTO ClassEnrollments VALUES (4, 17)
INSERT INTO ClassEnrollments VALUES (8, 17)
INSERT INTO ClassEnrollments VALUES (16, 17)
INSERT INTO ClassEnrollments VALUES (3, 17)
INSERT INTO ClassEnrollments VALUES (9, 18)
INSERT INTO ClassEnrollments VALUES (4, 18)
INSERT INTO ClassEnrollments VALUES (16, 18)
INSERT INTO ClassEnrollments VALUES (5, 18)
INSERT INTO ClassEnrollments VALUES (25, 18)
GO

INSERT INTO ClassEnrollments VALUES (1, 19)
INSERT INTO ClassEnrollments VALUES (2, 19)
INSERT INTO ClassEnrollments VALUES (3, 19)
INSERT INTO ClassEnrollments VALUES (4, 19)
INSERT INTO ClassEnrollments VALUES (5, 19)
INSERT INTO ClassEnrollments VALUES (6, 20)
INSERT INTO ClassEnrollments VALUES (7, 20)
INSERT INTO ClassEnrollments VALUES (8, 20)
INSERT INTO ClassEnrollments VALUES (9, 20)
INSERT INTO ClassEnrollments VALUES (10, 20)
INSERT INTO ClassEnrollments VALUES (11, 21)
INSERT INTO ClassEnrollments VALUES (12, 21)
INSERT INTO ClassEnrollments VALUES (13, 21)
INSERT INTO ClassEnrollments VALUES (14, 21)
INSERT INTO ClassEnrollments VALUES (15, 21)
INSERT INTO ClassEnrollments VALUES (16, 22)
INSERT INTO ClassEnrollments VALUES (17, 22)
INSERT INTO ClassEnrollments VALUES (18, 22)
INSERT INTO ClassEnrollments VALUES (19, 22)
INSERT INTO ClassEnrollments VALUES (20, 22)
INSERT INTO ClassEnrollments VALUES (21, 23)
INSERT INTO ClassEnrollments VALUES (22, 23)
INSERT INTO ClassEnrollments VALUES (23, 23)
INSERT INTO ClassEnrollments VALUES (24, 23)
INSERT INTO ClassEnrollments VALUES (25, 23)
GO



INSERT INTO ClassEnrollments VALUES (1, 24)
INSERT INTO ClassEnrollments VALUES (2, 24)
INSERT INTO ClassEnrollments VALUES (3, 24)
INSERT INTO ClassEnrollments VALUES (4, 24)
INSERT INTO ClassEnrollments VALUES (5, 24)
INSERT INTO ClassEnrollments VALUES (6, 25)
INSERT INTO ClassEnrollments VALUES (7, 25)
INSERT INTO ClassEnrollments VALUES (8, 25)
INSERT INTO ClassEnrollments VALUES (9, 25)
INSERT INTO ClassEnrollments VALUES (10, 25)
INSERT INTO ClassEnrollments VALUES (11, 26)
INSERT INTO ClassEnrollments VALUES (12, 26)
INSERT INTO ClassEnrollments VALUES (13, 26)
INSERT INTO ClassEnrollments VALUES (14, 26)
INSERT INTO ClassEnrollments VALUES (15, 26)
INSERT INTO ClassEnrollments VALUES (16, 27)
INSERT INTO ClassEnrollments VALUES (17, 27)
INSERT INTO ClassEnrollments VALUES (18, 27)
INSERT INTO ClassEnrollments VALUES (19, 27)
INSERT INTO ClassEnrollments VALUES (20, 27)
INSERT INTO ClassEnrollments VALUES (21, 28)
INSERT INTO ClassEnrollments VALUES (22, 28)
INSERT INTO ClassEnrollments VALUES (23, 28)
INSERT INTO ClassEnrollments VALUES (24, 28)
INSERT INTO ClassEnrollments VALUES (25, 28)
GO

INSERT INTO ClassEnrollments VALUES (1, 29)
INSERT INTO ClassEnrollments VALUES (2, 29)
INSERT INTO ClassEnrollments VALUES (3, 29)
INSERT INTO ClassEnrollments VALUES (4, 29)
INSERT INTO ClassEnrollments VALUES (5, 29)
INSERT INTO ClassEnrollments VALUES (6, 30)
INSERT INTO ClassEnrollments VALUES (7, 30)
INSERT INTO ClassEnrollments VALUES (8, 30)
INSERT INTO ClassEnrollments VALUES (9, 30)
INSERT INTO ClassEnrollments VALUES (10, 30)
INSERT INTO ClassEnrollments VALUES (11, 31)
INSERT INTO ClassEnrollments VALUES (12, 31)
INSERT INTO ClassEnrollments VALUES (13, 31)
INSERT INTO ClassEnrollments VALUES (14, 31)
INSERT INTO ClassEnrollments VALUES (15, 31)
INSERT INTO ClassEnrollments VALUES (16, 32)
INSERT INTO ClassEnrollments VALUES (17, 32)
INSERT INTO ClassEnrollments VALUES (18, 32)
INSERT INTO ClassEnrollments VALUES (19, 32)
INSERT INTO ClassEnrollments VALUES (20, 32)
INSERT INTO ClassEnrollments VALUES (21, 33)
INSERT INTO ClassEnrollments VALUES (22, 33)
INSERT INTO ClassEnrollments VALUES (23, 33)
INSERT INTO ClassEnrollments VALUES (24, 33)
INSERT INTO ClassEnrollments VALUES (25, 33)
GO

INSERT INTO ClassEnrollments VALUES (1, 34)
INSERT INTO ClassEnrollments VALUES (3, 34)
INSERT INTO ClassEnrollments VALUES (5, 34)
INSERT INTO ClassEnrollments VALUES (7, 34)
INSERT INTO ClassEnrollments VALUES (9, 34)
INSERT INTO ClassEnrollments VALUES (11, 35)
INSERT INTO ClassEnrollments VALUES (13, 35)
INSERT INTO ClassEnrollments VALUES (15, 35)
INSERT INTO ClassEnrollments VALUES (17, 35)
INSERT INTO ClassEnrollments VALUES (19, 35)
INSERT INTO ClassEnrollments VALUES (21, 36)
INSERT INTO ClassEnrollments VALUES (22, 36)
INSERT INTO ClassEnrollments VALUES (23, 36)
INSERT INTO ClassEnrollments VALUES (24, 36)
INSERT INTO ClassEnrollments VALUES (25, 36)
GO


INSERT INTO ClassEnrollments VALUES (2, 37)
INSERT INTO ClassEnrollments VALUES (4, 37)
INSERT INTO ClassEnrollments VALUES (6, 37)
INSERT INTO ClassEnrollments VALUES (8, 37)
INSERT INTO ClassEnrollments VALUES (10, 37)
INSERT INTO ClassEnrollments VALUES (12, 38)
INSERT INTO ClassEnrollments VALUES (14, 38)
INSERT INTO ClassEnrollments VALUES (16, 38)
INSERT INTO ClassEnrollments VALUES (18, 38)
INSERT INTO ClassEnrollments VALUES (20, 38)
GO


INSERT INTO ClassEnrollments VALUES (3, 39)
INSERT INTO ClassEnrollments VALUES (6, 39)
INSERT INTO ClassEnrollments VALUES (9, 39)
INSERT INTO ClassEnrollments VALUES (12, 39)
INSERT INTO ClassEnrollments VALUES (15, 39)
INSERT INTO ClassEnrollments VALUES (18, 40)
INSERT INTO ClassEnrollments VALUES (21, 40)
INSERT INTO ClassEnrollments VALUES (23, 40)
INSERT INTO ClassEnrollments VALUES (24, 40)
INSERT INTO ClassEnrollments VALUES (25, 40)
GO